# version: '3'
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     ports:
#       - "3000:3000"
#     volumes:
#       - /app/node_modules
#       - .:/app
#   tests:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     volumes:
#       - /app/node_modules
#       - .:/app
#     command: ["npm", "run", "test"]
#   prod:
#     build: .
#     ports:
#       - "8080:80"
  

version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
