name: Deploy Complex Application
on:
  push:
    branches:
      - master

jobs:
  build-test-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Build Dev Client
        uses: docker/build-push-action@v2
        with:
          context: complex/client
          file: complex/client/Dockerfile.dev
          tags: rushi1006/docker-client-test:latest

      - name: Run Client Test
        run: docker run -e CI=true rushi1006/docker-client-test:latest npm run test

      - name: Build Dev Server
        uses: docker/build-push-action@v2
        with:
          context: complex/server
          file: complex/server/Dockerfile.dev
          tags: rushi1006/docker-server-test:latest

      - name: Run Server Test
        run: docker run -e CI=true rushi1006/docker-server-test:latest npm run test

      - name: Build Worker Client
        uses: docker/build-push-action@v2
        with:
          context: complex/worker
          file: complex/worker/Dockerfile.dev
          tags: rushi1006/docker-worker-test:latest

      - name: Run Worker Test
        run: docker run -e CI=true rushi1006/docker-worker-test:latest npm run test

  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build client container.
        uses: docker/build-push-action@v2
        with:
          context: complex/client
          push: true
          file: complex/client/Dockerfile
          tags: rushi1006/complex-client:latest

      - name: Build nginx container
        uses: docker/build-push-action@v2
        with:
          context: complex/nginx
          push: true
          file: complex/nginx/Dockerfile
          tags: rushi1006/complex-nginx:latest

      - name: Build server container
        uses: docker/build-push-action@v2
        with:
          context: complex/server
          push: true
          file: complex/server/Dockerfile
          tags: rushi1006/complex-server:latest

      - name: Build worker container
        uses: docker/build-push-action@v2
        with:
          context: complex/worker
          push: true
          file: complex/worker/Dockerfile
          tags: rushi1006/complex-worker:latest
